[build]
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"
  PYTHON_SETUP_PY_READ = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 